### ISSUE TITLE
README install doesn't mention proyecto

### ISSUE THREAD

**Issue by dgretton** [rotolonico/FirebaseWebGL#1]
Hi, thanks for this phenomenal repository, it's just what I needed.

The installation instructions say I should copy the FirebaseWebGL directory into my assets folder, but this by itself is not sufficient; it threw errors involving "proyecto." I also needed to copy the RestClient directory, which seems to have fixed it. Hopefully this is all, but unsure; recommend updating the readme. thank you!

**Comment by rotolonico** [comment]
Thanks, I had missed that. I am glad this repo helped you!
