### ISSUE TITLE
Best way to get new key back from push?

### ISSUE THREAD

**Issue by Vixxd** [rotolonico/FirebaseWebGL#10]
I was wondering what the plugin's equivalent is to this web call?

https://firebase.google.com/docs/database/web/read-and-write#update_specific_fields
```
  // Get a key for a new Post.
  var newPostKey = firebase.database().ref().child('posts').push().key;
```

I am adding scores to a table and would like to get the score id returned immediately after pushing the score. I will eventually work it out (and will update the post when I do), but just looking to see if anyone else has their implementation at hand!

**Comment by rotolonico** [comment]
I don't think there's a way to do it right now, but you can change the library code to make it work! 
In `Assets/FirebaseWebGL/Plugins/firebasedatabase.jslib` on line 48, the callback is currently returning `"Success: " + parsedValue + " was pushed to " + parsedPath`. You can change that to return the information you want to c#; I think changing that string to unused.key will do the trick as the firebase javascript SDK push request returns the pushed object in its callback
