### ISSUE TITLE
Any joy with the Analytics package

### ISSUE THREAD

**Issue by Reddevildragg** [rotolonico/FirebaseWebGL#2]
More of a question than an issues.

But have you had any job getting the firebase analytics package working with webGL or any pointers on trying to get it working?

At its core i understand i need a .jslib file with the analytics functions inside and then use the dllImport to call the functions, but cant find a .jslib for this feature/know where to start to create one.

**Comment by rotolonico** [comment]
Hey, sorry for the late reply.
But yeah a Firebase Analytics package would work a similar way. You'd need a .jslib file and a new bridge with the extern functions to communicate back to Unity.

You can use the official [web sdk documentation](https://firebase.google.com/docs/reference/js/firebase.analytics) functions in your javascript and everything should work smoothly. Feel free to ask me if there is anything, in particular, you need help with
