### ISSUE TITLE
Sign in with google and facebook Not work

### ISSUE THREAD

**Issue by dareerahmadmufti** [rotolonico/FirebaseWebGL#3]
When try to play the demo scene ("AuthExampleScene") in the project, to test the sign in with google and Facebook functionality. 
It doesn't work and produce an error:
"An error occurred running the Unity content on this page. See your browser JavaScript console for more info. The error was:
ReferenceError: unityInstance is not defined".

I have placed the required code (firebase project setting code) in the index.html and enabled both (google and Facebook) of them in the firebase console also. Also try many things, but nothing worked for me.

Setup:
- UNITY 2019.4.24f1 with WebGL support
- VS Code

Also followed the links:
https://firebase.google.com/docs/auth/web/facebook-login
https://firebase.google.com/docs/auth/web/google-signin

**Comment by rotolonico** [comment]
Hey apologizes for the late reply. If you are still struggling with this, when unity generates the WebGL build I believe on some templates it called the instance gameInstance instead of unityInstance, so you might want to duplicate the variable to accommodate for the library code.
