### ISSUE TITLE
Firebase Database not working properly for PutJSON

### ISSUE THREAD

**Issue by justLukass** [rotolonico/FirebaseWebGL#4]
### --- ISSUE ---
This project is awesome but I found out when I call the PostJSON function:

`PostJSON: function(path, value, objectName, callback, fallback) { ...
firebase.database().ref(parsedPath).set(parsedValue).then(function(unused) {...}
}`

and I pass JSON string from C# to its 'value' parameter, the realtime databse will not receive properly formatted JSON but some escaped string version of it like this:

`"{\"Player\":\"Lukas\"}"`

which prevents firebase to properly construct database structure since it treats this like a one line string (which it is).

### --- SOLUTION ---
After hours of searching I found out that set() function expects JavaScript object, not a JSON string so instead of calling

`set(parsedValue)`

I had to use JSON.parse like this:

`set(JSON.parse(parsedValue))`

which converts 'parsedValue' string into proper JS object. Also I found [here](https://emscripten.org/docs/introducing_emscripten/release_notes.html?highlight=pointer_stringify) that Pointer_stringify function is obsolete and is being replaced by [UTF8ToString](https://emscripten.org/docs/api_reference/preamble.js.html#conversion-functions-strings-pointers-and-arrays). 

As soon as I added that JSON.parse call and replaced all Pointer_stringify calls by UTF8ToString it all stared working although the Pointer_stringify replacement might not be necessary here. 

I hope this helps someone in the future.

**JL**

**Comment by rotolonico** [comment]
Hey, thanks for reporting the issue. I have fixed it in this version for Put, Post, and Update functions
