### ISSUE TITLE
only GetJson function works

### ISSUE THREAD

**Issue by mkjuice** [rotolonico/FirebaseWebGL#9]
GetJSON works as expected in my game but Post, Push, and Update do not work. I've imported each of them but still get the error:
{"stack":"SyntaxError: Unexpected token p in JSON at position 0\n    at JSON.parse  (<anonymous>)\n at_PostJSON

any tips?

**Comment by mkjuice** [comment]
Update: After starting a new project ive found that the post method does work if i input a number into the TMP_InputField. Letters do not work though

**Comment by rotolonico** [comment]
Hey, so the Post, Push and Update methods actually accept JSON serialized values. This is so you can push more complex objects with just one call (like in the Javascript SDK). So if you want to push 'hello', you have to insert "hello" in the input field (with the quotation included)
